/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiPublicMealdbSplatRouteImport } from './routes/api/public/mealdb.$'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMealdbSplatRoute = ApiPublicMealdbSplatRouteImport.update({
  id: '/api/public/mealdb/$',
  path: '/api/public/mealdb/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/mealdb/$': typeof ApiPublicMealdbSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/mealdb/$': typeof ApiPublicMealdbSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/mealdb/$': typeof ApiPublicMealdbSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/auth/callback' | '/api/public/mealdb/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/auth/callback' | '/api/public/mealdb/$'
  id: '__root__' | '/' | '/$' | '/auth/callback' | '/api/public/mealdb/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicMealdbSplatRoute: typeof ApiPublicMealdbSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mealdb/$': {
      id: '/api/public/mealdb/$'
      path: '/api/public/mealdb/$'
      fullPath: '/api/public/mealdb/$'
      preLoaderRoute: typeof ApiPublicMealdbSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicMealdbSplatRoute: ApiPublicMealdbSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
